// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl5V3lh7IXiZORqChOnRBkiGuKFqjaOlE',
    appId: '1:557221178493:web:3e343bbffcab966a085514',
    messagingSenderId: '557221178493',
    projectId: 'flutter-test-1-acc7c',
    authDomain: 'flutter-test-1-acc7c.firebaseapp.com',
    storageBucket: 'flutter-test-1-acc7c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPNv3pMzFy9RNXpl314t8MKG7vPOyZ5vQ',
    appId: '1:557221178493:android:6b74cd6a05b2766c085514',
    messagingSenderId: '557221178493',
    projectId: 'flutter-test-1-acc7c',
    storageBucket: 'flutter-test-1-acc7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw9NBNuHQdDD9_N_aw5OjPPYZOw3RLI18',
    appId: '1:557221178493:ios:a157638cc43830d0085514',
    messagingSenderId: '557221178493',
    projectId: 'flutter-test-1-acc7c',
    storageBucket: 'flutter-test-1-acc7c.appspot.com',
    androidClientId: '557221178493-e0dnt1dsm41ab6lrlc5haqreqp85siie.apps.googleusercontent.com',
    iosClientId: '557221178493-ss0621brrskm8318ep7gs4j0j88th6m2.apps.googleusercontent.com',
    iosBundleId: 'com.example.denverTest3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw9NBNuHQdDD9_N_aw5OjPPYZOw3RLI18',
    appId: '1:557221178493:ios:a157638cc43830d0085514',
    messagingSenderId: '557221178493',
    projectId: 'flutter-test-1-acc7c',
    storageBucket: 'flutter-test-1-acc7c.appspot.com',
    androidClientId: '557221178493-e0dnt1dsm41ab6lrlc5haqreqp85siie.apps.googleusercontent.com',
    iosClientId: '557221178493-ss0621brrskm8318ep7gs4j0j88th6m2.apps.googleusercontent.com',
    iosBundleId: 'com.example.denverTest3',
  );
}
